spring:
  application:
    name: movies-app
  datasource:
    url: jdbc:mysql://localhost:3306/moviesapp_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: moviesapp_user
    password: moviesapp_pass
  jpa:
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml


award-winnings-file: csv/academy_awards.csv
